// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileShare(arg1:string,arg2:string):Promise<string>;

export function GetMultiAddress():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Message(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialogBox():Promise<string>;
