// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileShare(arg1, arg2) {
  return window['go']['app']['App']['FileShare'](arg1, arg2);
}

export function GetMultiAddress() {
  return window['go']['app']['App']['GetMultiAddress']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function Message(arg1, arg2) {
  return window['go']['app']['App']['Message'](arg1, arg2);
}
